name: pytest

on: [pull_request]
env:
  COVERAGE_SINGLE: 60
  COVERAGE_TOTAL: 60

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
          ref: ${{github.event.pull_request.head.ref}}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Git Setup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git init
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
